In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("HR-Employee-Attrition.csv")

In [3]:
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [4]:
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [6]:
data.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [7]:
columns_to_keep = ['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'HourlyRate', 'JobRole','YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
              'YearsWithCurrManager']
columns_to_drop = [
       'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender','JobInvolvement', 'JobLevel','JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       ]

In [8]:
len(columns_to_keep)

13

In [9]:
len(columns_to_drop)

22

In [10]:
data.drop(columns = columns_to_drop, inplace = True)

In [11]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'HourlyRate', 'JobRole',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [12]:
data.head(3).iloc[ :,4:10]

,Department,DistanceFromHome,Education,HourlyRate,JobRole,YearsAtCompany
0,Sales,1,2,94,Sales Executive,6
1,Research & Development,8,1,61,Research Scientist,10
2,Research & Development,2,2,92,Laboratory Technician,0

In [13]:
data.shape

(1470, 13)

In [14]:
data[['Age', 'Attrition']]

      Age Attrition
0      41       Yes
1      49        No
2      37       Yes
3      33        No
4      27        No
...   ...       ...
1465   36        No
1466   39        No
1467   27        No
1468   49        No
1469   34        No

[1470 rows x 2 columns]

# 1st Method

In [15]:
new_data = data[columns_to_keep]

# 2nd Method

In [16]:
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [17]:
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,HourlyRate,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [18]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'HourlyRate', 'JobRole',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [19]:
data = data.rename(columns = {"DistanceFromHome": "DistanceHome"})

In [20]:
data = data.rename(columns = {"DailyRate": "DailyWage", "HourlyRate": "HourlyWage"})

In [21]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [22]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyWage', 'Department',
       'DistanceHome', 'Education', 'HourlyWage', 'JobRole', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [23]:
data.duplicated().value_counts()

False    1470
Name: count, dtype: int64

In [24]:
type(data.duplicated())

pandas.core.series.Series

In [25]:
data.drop_duplicates(inplace = True)

In [26]:
data.shape

(1470, 13)

In [27]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [28]:
data[data["Attrition"] == "Yes"]["Attrition"].unique()

array(['Yes'], dtype=object)

In [29]:
type(data["BusinessTravel"][1])

str

In [30]:
modify_data = data.copy()

In [31]:
modify_data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [32]:
data["BusinessTravel"] = data["BusinessTravel"].str.replace("_"," ")

In [33]:
modify_data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

# remove Nan values

data.isna().sum()

In [34]:
data.isna().sum()

Age                        0
Attrition                  0
BusinessTravel             0
DailyWage                  0
Department                 0
DistanceHome               0
Education                  0
HourlyWage                 0
JobRole                    0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [35]:
data.dropna(inplace = True)

In [36]:
data = data.dropna()

In [37]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,No,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,Yes,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,No,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,No,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,No,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,No,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,No,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,No,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [38]:
data["Attrition"] = data["Attrition"].apply(lambda x: 1 if x == "Yes" else 0)

In [39]:
data

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,0,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,0,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,0,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,0,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [40]:
data.to_csv("HR-Employee-Attrition-Cleaned.csv", index = False)

In [41]:
data.to_excel("HR-Employee-Attrition-Cleaned.xlsx", index = False)

In [42]:
pd.read_csv("HR-Employee-Attrition-Cleaned.csv")

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,0,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,0,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,0,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,0,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2

In [43]:
pd.read_excel("HR-Employee-Attrition-Cleaned.xlsx")

,Age,Attrition,BusinessTravel,DailyWage,Department,DistanceHome,Education,HourlyWage,JobRole,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel Rarely,1102,Sales,1,2,94,Sales Executive,6,4,0,5
1,49,0,Travel Frequently,279,Research & Development,8,1,61,Research Scientist,10,7,1,7
2,37,1,Travel Rarely,1373,Research & Development,2,2,92,Laboratory Technician,0,0,0,0
3,33,0,Travel Frequently,1392,Research & Development,3,4,56,Research Scientist,8,7,3,0
4,27,0,Travel Rarely,591,Research & Development,2,1,40,Laboratory Technician,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,Travel Frequently,884,Research & Development,23,2,41,Laboratory Technician,5,2,0,3
1466,39,0,Travel Rarely,613,Research & Development,6,1,42,Healthcare Representative,7,7,1,7
1467,27,0,Travel Rarely,155,Research & Development,4,3,87,Manufacturing Director,6,2,0,3
1468,49,0,Travel Frequently,1023,Sales,2,3,63,Sales Executive,9,6,0,8
1469,34,0,Travel Rarely,628,Research & Development,8,3,82,Laboratory Technician,4,3,1,2